# Redes Neuronales Recurrentes (RNN)

## 1. Vectorización de texto

### 1.1. One-hot encoding

In [2]:
from numpy import array
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

doc = "Me gusta el Deep Learning"

doc = doc.lower()
doc = doc.split()
values = array(doc)
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

['me' 'gusta' 'el' 'deep' 'learning']
[4 2 1 0 3]
[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


c:\Users\pepel\.conda\envs\PySpace310\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


### 1.2. Embedding layer de Keras

In [ ]:
from tensorflow.keras import layers

layers.Embedding(input_dim=vocab_size, output_dim=embedding_dim)

## 2. Programando una RNN: Generación de texto

### 2.1. Descarga y preprocesado de los datos

In [3]:
import os

path_txt = os.path.join("DeepLearning-Introduccion-practica-con-Keras-PRIMERA-PARTE.txt")

text = open(path_txt, 'rb').read().decode(encoding='utf-8')
print("Longitud del texto: {} caráceters".format(len(text)))

vocab = sorted(set(text))
print("El texto está compuesto de estos {} caráceteres:".format(len(vocab)))
print(f"\n{vocab}")

Longitud del texto: 203251 caráceters
El texto está compuesto de estos 92 caráceteres:

['\n', '\r', ' ', '!', '"', '#', '%', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\xad', 'ÿ', 'Š', '‡', '…']


In [5]:
import numpy as np

char2dix = {u:i for i, u in enumerate(vocab)}
idx2char = np.array(vocab)

In [6]:
for char, _ in zip(char2dix, range(len(vocab))):
    print(" {:4s}: {:3d},".format(repr(char), char2dix[char]))

 '\n':   0,
 '\r':   1,
 ' ' :   2,
 '!' :   3,
 '"' :   4,
 '#' :   5,
 '%' :   6,
 "'" :   7,
 '(' :   8,
 ')' :   9,
 '*' :  10,
 '+' :  11,
 ',' :  12,
 '-' :  13,
 '.' :  14,
 '/' :  15,
 '0' :  16,
 '1' :  17,
 '2' :  18,
 '3' :  19,
 '4' :  20,
 '5' :  21,
 '6' :  22,
 '7' :  23,
 '8' :  24,
 '9' :  25,
 ':' :  26,
 ';' :  27,
 '<' :  28,
 '=' :  29,
 '>' :  30,
 '?' :  31,
 '@' :  32,
 'A' :  33,
 'B' :  34,
 'C' :  35,
 'D' :  36,
 'E' :  37,
 'F' :  38,
 'G' :  39,
 'H' :  40,
 'I' :  41,
 'J' :  42,
 'K' :  43,
 'L' :  44,
 'M' :  45,
 'N' :  46,
 'O' :  47,
 'P' :  48,
 'Q' :  49,
 'R' :  50,
 'S' :  51,
 'T' :  52,
 'U' :  53,
 'V' :  54,
 'W' :  55,
 'X' :  56,
 'Y' :  57,
 '[' :  58,
 ']' :  59,
 '_' :  60,
 'a' :  61,
 'b' :  62,
 'c' :  63,
 'd' :  64,
 'e' :  65,
 'f' :  66,
 'g' :  67,
 'h' :  68,
 'i' :  69,
 'j' :  70,
 'k' :  71,
 'l' :  72,
 'm' :  73,
 'n' :  74,
 'o' :  75,
 'p' :  76,
 'q' :  77,
 'r' :  78,
 's' :  79,
 't' :  80,
 'u' :  81,
 'v' :  82,
 'w'

In [7]:
text_as_int = np.array([char2dix[c] for c in text])

In [8]:
print("texto: {}".format(repr(text[:50])))
print("{}".format(repr(text_as_int[:50])))

texto: 'Prologo\r\nEn 1953, Isaac Asimov publico Segunda Fun'
array([48, 78, 75, 72, 75, 67, 75,  1,  0, 37, 74,  2, 17, 25, 21, 19, 12,
        2, 41, 79, 61, 61, 63,  2, 33, 79, 69, 73, 75, 82,  2, 76, 81, 62,
       72, 69, 63, 75,  2, 51, 65, 67, 81, 74, 64, 61,  2, 38, 81, 74])


### 2.2. Preparación de los datos para ser usados por la RNN

In [9]:
import tensorflow as tf

char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

seq_length = 100

sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

In [10]:
for item in sequences.take(10):
    print(repr(''.join(idx2char[item.numpy()])))

'Prologo\r\nEn 1953, Isaac Asimov publico Segunda Fundacion, el tercer libro de la saga de la Fundacion '
'(o el decimotercero segun otras fuentes, este es un tema de debate). En Segunda Fundacion aparece por'
' primera vez Arkady Darell, uno de los principales personajes de la parte final de la saga. En su pri'
'mera escena, Arkady, que tiene 14 anos, esta haciendo sus tareas escolares. En concreto, una redaccio'
'n que lleva por titulo ?El Futuro del Plan Sheldon?. Para hacer la redaccion, Arkady esta utilizando '
'un ?transcriptor?,un dispositivo que convierte su voz en palabras escritas. Este tipo de dispositivo,'
' que para Isaac Asimov era ciencia ficcion en 1953, lo tenemos al alcance de la mano en la mayoria de'
' nuestros smartphones, y el Deep Learning es uno de los responsables de que ya tengamos este tipo de '
'aplicaciones, siendo la tecnologia otro de ellos.En la actualidad disponemos de GPUs (Graphics Proces'
'sor Units), que solo cuestan alrededor de 100 euros, que esta

In [12]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

In [13]:
for input_example, target_example in dataset.take(1):
    print("Input data: ", repr(''.join(idx2char[input_example.numpy()])))
    print("Target data: ", repr(''.join(idx2char[target_example.numpy()])))

Input data:  'Prologo\r\nEn 1953, Isaac Asimov publico Segunda Fundacion, el tercer libro de la saga de la Fundacion'
Target data:  'rologo\r\nEn 1953, Isaac Asimov publico Segunda Fundacion, el tercer libro de la saga de la Fundacion '


In [14]:
print(dataset)

<MapDataset element_spec=(TensorSpec(shape=(100,), dtype=tf.int32, name=None), TensorSpec(shape=(100,), dtype=tf.int32, name=None))>


In [15]:
BATCH_SIZE = 64

BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

print(dataset)

<BatchDataset element_spec=(TensorSpec(shape=(64, 100), dtype=tf.int32, name=None), TensorSpec(shape=(64, 100), dtype=tf.int32, name=None))>


### 2.3. Construcción del modelo RNN

In [16]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
    model = Sequential()
    model.add(Embedding(
        input_dim=vocab_size,
        output_dim=embedding_dim,
        batch_input_shape=[batch_size, None]
    ))
    model.add(LSTM(
        rnn_units,
        return_sequences=True,
        stateful=True,
        recurrent_initializer='glorot_uniform'
    ))
    model.add(Dense(vocab_size))
    return model

vocab_size = len(vocab)
embedding_dim = 256
rnn_units = 1024

model = build_model(
    vocab_size=vocab_size,
    embedding_dim=embedding_dim,
    rnn_units=rnn_units,
    batch_size=BATCH_SIZE
)

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (64, None, 256)           23552     
                                                                 
 lstm (LSTM)                 (64, None, 1024)          5246976   
                                                                 
 dense (Dense)               (64, None, 92)            94300     
                                                                 
Total params: 5,364,828
Trainable params: 5,364,828
Non-trainable params: 0
_________________________________________________________________


In [18]:
for input_example_batch, target_example_batch in dataset.take(1):
    print("Input:", input_example_batch.shape, "# (batch_size, sequence_length)")
    print("Target:", target_example_batch.shape, "# (batch_size, sequence_length)")

Input: (64, 100) # (batch_size, sequence_length)
Target: (64, 100) # (batch_size, sequence_length)


In [19]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print("Prediction: ", example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")

Prediction:  (64, 100, 92) # (batch_size, sequence_length, vocab_size)


In [20]:
sampled_indices = tf.random.categorical(
    example_batch_predictions[0],
    num_samples=1)

sampled_indices_characters = tf.squeeze(
    sampled_indices,
    axis=-1
).numpy()

In [21]:
print(sampled_indices_characters)

[90 68 44 86 45 51 66 86 31 65 66 60 58 27 65 15 34 11 30 23 70 61 16 82
 39 88 24 52 49 77 14 66 70 91 83  8 80  3 59 37 39 78 62 79 47 78 24 18
 47 21 82 54 53  8  7 91 39 67 40 82 44 48 84 30 50 91 48  6 35 31 73 72
 48 37 30 43 52 89 36 36 19 10  3 37 30 10 39 41 12 16 32 44 34 78 34  3
 32 31 64 44]


### 2.4. Entrenamiento del modelo RNN

### 2.5. Generación de texto usando el modelo RNN

### 2.6. Generando texto falso de Shakespeare